[package]
name = "everstake-landing-docs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
solana-client = "4.2.2"
solana-sdk = "4.0.0"
solana-message = "4.4.1"
solana-transaction = { version = "4.1.6", features = ["wincode"] }
tokio = { version = "1.39", features = ["macros", "rt-multi-thread", "net", "time", "io-util"] }
quinn = "0.11.3"
rustls = { version = "0.23.15", default-features = false }
wincode = "0.5.5"
solana-tls-utils = "4.2.2"
solana-system-interface = { version = "3.2.0", features = ["bincode"] }
reqwest = "0.12.26"
solana-rpc-client = "4.2.2"
